YAML_PRETTIER_FILTER_REGEX_EXCLUDE: (specs/)
YAML_V8R_FILTER_REGEX_EXCLUDE: (specs/)
DISABLE_LINTERS:
  - SPELL_CSPELL
  - COPYPASTE_JSCPD
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
PYTHON_BLACK_CONFIG_FILE: pyproject.toml
FORMATTERS_DISABLE_ERRORS: false
PRINT_ALPACA: false
